#!/bin/bash
#run_deploy

set -x -e

source $(pwd)/efs-volume-release/scripts/ci/utils.sh
check_param BOSH_TARGET
check_param BOSH_USERNAME
check_param BOSH_PASSWORD

version=`cat efs-volume-version/number`
pushd efs-volume-release

bosh -n --parallel 10 create release --version $version --name efs-volume --force --with-tarball

bosh -n target ${BOSH_TARGET}
bosh -n login ${BOSH_USERNAME} ${BOSH_PASSWORD}
bosh upload release dev_releases/efs-volume/efs-volume*.tgz
mv dev_releases/efs-volume/efs-volume-$version.tgz ../created-efs-volume-release/efsvolume-$version.tgz
popd
