#!/bin/bash

set -x -e

version=`cat efs-volume-version/number`
tarball_name=efs-volume-$version.tgz

pushd efs-volume-release
  bosh -n create-release --version=$version --force --tarball=$tarball_name
  mv $tarball_name ../created-efs-volume-release
popd
