#!/bin/bash

set -x -e

version=`cat efs-volume-version/number`
pushd efs-volume-release

bosh -n --parallel 10 create release --version $version --name efs-volume --force --with-tarball
mv dev_releases/efs-volume/efs-volume-$version.tgz ../created-efs-volume-release/efsvolume-$version.tgz
popd
