#!/bin/bash
# vim: set ft=sh

set -e

cd efs-volume-release/

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

go get github.com/onsi/ginkgo/ginkgo

# TODO this should go in the dockerfile
apt-get -q -y install nfs-common

./scripts/run-certification-tests
