#!/bin/bash

set -e

cd `dirname $0`
cd ..

go build -o "$HOME/efsdriver" "src/code.cloudfoundry.org/efsdriver/cmd/efsdriver/main.go"

go get -t code.cloudfoundry.org/docker-driver-integration-tests

# UNIX SOCKET TESTS
export FIXTURE_FILENAME=$1
/bin/bash scripts/startdriver_unix.sh
pushd src/code.cloudfoundry.org/docker-driver-integration-tests
    ginkgo
popd
/bin/bash scripts/stopdriver.sh


rm -rf $HOME/certs
rm $HOME/efsdriver
