#!/bin/bash

set -e

scripts_path=./$(dirname $0)
eval $($scripts_path/get_paths.sh)

pushd src/github.com/cloudfoundry-incubator/efsdriver
  ginkgo -r -keepGoing -p -trace -randomizeAllSpecs -progress --race "$@"
popd
