#!/bin/bash

set -e -x

# ensure gosub is installed (this will recompile it only if necessary)
go get github.com/vito/gosub
go install github.com/vito/gosub

{
  # gosub list -app code.cloudfoundry.org/localdriver/cmd/... \
  gosub list -app code.cloudfoundry.org/efsbroker/cmd/... \

  # separate test and binary dependencies
  #gosub list -test code.cloudfoundry.org/localdriver/...
  gosub list -test code.cloudfoundry.org/efsbroker/...
  gosub list -test code.cloudfoundry.org/persi-acceptance-tests/...
} > /tmp/packages

cat /tmp/packages | xargs gosub sync
